Not break munging
I still don't know why but a None object ended up in the `s` variable
breaking the `replace` function:

```
AttributeError: 'NoneType' object has no attribute 'replace'
```

Due to lack of complete understanding of the tool and my debug-foo not
issuing any results I'm just hotfixing it with a try/catch.

Please feel free to use a proper fixing.